<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<a href="/login"> Login </a>
<a href="/registration"> Registration </a>
<!--<form method = "GET" action = "registration.ftlh">
    <table>
        <tr>
            <td>
                <input type = "submit" value = "Login"/>
            </td>
        </tr>
    </table>
</form>
<form method = "GET" action = "registration.ftlh">
    <table>
        <tr>
            <td>
                <input type = "submit" value = "Registration"/>
            </td>
        </tr>
    </table>
</form>-->
</body>
</html>